In [14]:
# importing libraries
import pandas as pd
import numpy as np

In [15]:
# read dataset
books= pd.read_csv('book.csv',encoding='latin')

In [16]:
books

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [17]:
# droping unwanted column
books.drop('Unnamed: 0',inplace=True,axis=1)
books

User.ID                                         Book.Title  Book.Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [18]:
# renaming column names
books=books.rename(columns={'User.ID':'ID', 'Book.Title':'Title', 'Book.Rating':'Rating'})
books

ID                                              Title  Rating
0     276726                                Classical Mythology       5
1     276729                                       Clara Callan       3
2     276729                               Decision in Normandy       6
3     276736  Flu: The Story of the Great Influenza Pandemic...       8
4     276737                             The Mummies of Urumchi       6
...      ...                                                ...     ...
9995  162121       American Fried: Adventures of a Happy Eater.       7
9996  162121                              Cannibal In Manhattan       9
9997  162121                    How to Flirt: A Practical Guide       7
9998  162121                                           Twilight       8
9999  162129                       Kids Say the Darndest Things       6

[10000 rows x 3 columns]

In [19]:
# sorting id colunm from asending order
books=books.sort_values('ID')
books.head(30)

ID                                              Title  Rating
2401   8                                              Wings       5
2400   8  The Western way: A practical guide to the West...       5
2399   8                            Ancient Celtic Romances       5
2402   8                                           Truckers       5
2405   8                                  The Art Of Celtia       7
2403   8                Keepers of the Earth Teachers Guide       6
2404   8                            The Celts Activity Book       6
2406   9   The Book of Kells: Selected Plates in Full Color       6
2407  10                                SINGLE &amp; SINGLE       6
2408  12                                     Apocalypse Wow      10
2409  14                                               COPS       5
2410  14               A Cold Heart: An Alex Delaware Novel       5
2411  14                                         Dead Sleep       6
2412  16           Random Acts Of Management:A Dilbert Book       9
2413  17         Conversations With Dogbert: A Dilbert Book       7
2414  17  The Dilbert Bunch: A Dilbert Book (Main Street...       5
2415  17   You Don't Need Experience if You've Got Attitude       6
2416  17  The Boss: Nameless, Blameless and Shameless (A...       3
2417  19                                    The Murder Book       7
2418  22                                       Shock-Trauma       7
2419  26                                         The Jester      10
2420  26  Jupiter's Bones: A Novel (Peter Decker &amp; R...       9
2421  32  Silent Witness: How Forensic Anthropology Is U...       8
2422  39                              No Witnesses: A Novel       8
2423  39                                   The Hancock Boys       7
2424  42  Dead Reckoning: The New Science of Catching Ki...       7
2425  44                                           Roadwork       8
2426  51                                         Watermelon       9
2430  53                                               Prey       9
2427  53                                         Sick Puppy       3

- from above we can say that user 8 have read 7 different books and his giving ratings is average above 5.

In [26]:
from pandas import Grouper
books.groupby(pd.Grouper(key="ID")).count()        

Title  Rating
ID                   
8           7       7
9           1       1
10          1       1
12          1       1
14          3       3
...       ...     ...
278846      1       1
278849      1       1
278851     14      14
278852      1       1
278854      6       6

[2182 rows x 2 columns]

In [32]:
#number of unique users in the dataset
len(books.ID.unique())      

2182

In [33]:
# count of rating column
books['Rating'].value_counts()

8     2283
7     2076
10    1732
9     1493
5     1007
6      920
4      237
3      146
2       63
1       43
Name: Rating, dtype: int64

- maximum user gives 8 ratings

In [34]:
books.Title.unique()

array(['Classical Mythology', 'Clara Callan', 'Decision in Normandy', ...,
       'How to Flirt: A Practical Guide', 'Twilight',
       'Kids Say the Darndest Things'], dtype=object)

In [35]:
#count of unique books
len(books.Title.unique())        

9659

In [36]:
books.Title.value_counts().head(50)

Fahrenheit 451                                                    5
Charlie and the Chocolate Factory                                 4
The Subtle Knife (His Dark Materials, Book 2)                     4
Vanished                                                          4
Ender's Game (Ender Wiggins Saga (Paperback))                     4
Stardust                                                          4
The Amber Spyglass (His Dark Materials, Book 3)                   4
Life Is Elsewhere                                                 3
The Golden Compass (His Dark Materials, Book 1)                   3
The Hitchhiker's Guide to the Galaxy                              3
It                                                                3
The Hero and the Crown                                            3
Pigs in Heaven                                                    3
The Face                                                          3
Wuthering Heights                               

- most read book is Fahrenheit 451.

In [37]:
# deleting duplicate entries
books=books.drop_duplicates()

In [38]:
#duplicate entry of user with same book
books[books.duplicated(subset=["ID","Title"])]

ID                        Title  Rating
2001  278418     White Oleander : A Novel       5
3792    1211                  Black House       9
4745    2033               The First Time       2
5219    2276  In the Beauty of the Lilies      10
9945  162052                         Rose       8

In [39]:
bookclean=books.drop_duplicates(subset=["ID","Title"])
bookclean

ID                                              Title  Rating
0     276726                                Classical Mythology       5
1     276729                                       Clara Callan       3
2     276729                               Decision in Normandy       6
3     276736  Flu: The Story of the Great Influenza Pandemic...       8
4     276737                             The Mummies of Urumchi       6
...      ...                                                ...     ...
9995  162121       American Fried: Adventures of a Happy Eater.       7
9996  162121                              Cannibal In Manhattan       9
9997  162121                    How to Flirt: A Practical Guide       7
9998  162121                                           Twilight       8
9999  162129                       Kids Say the Darndest Things       6

[9993 rows x 3 columns]

In [40]:
#making sparse matrix
user_books = bookclean.pivot(index='ID',
                                 columns='Title',
                                 values='Rating')

In [41]:
user_books

Title    Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
ID                                                                         
8                        NaN                                         NaN   
9                        NaN                                         NaN   
10                       NaN                                         NaN   
12                       NaN                                         NaN   
14                       NaN                                         NaN   
...                      ...                                         ...   
278846                   NaN                                         NaN   
278849                   NaN                                         NaN   
278851                   NaN                                         NaN   
278852                   NaN                                         NaN   
278854                   NaN                                         NaN   

Title    Repairing PC Drives &amp  '48  \
ID                                       
8                             NaN  NaN   
9                             NaN  NaN   
10                            NaN  NaN   
12                            NaN  NaN   
14                            NaN  NaN   
...                           ...  ...   
278846                        NaN  NaN   
278849                        NaN  NaN   
278851                        NaN  NaN   
278852                        NaN  NaN   
278854                        NaN  NaN   

Title   'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
ID                                                                              
8                                                     NaN                       
9                                                     NaN                       
10                                                    NaN                       
12                                                    NaN                       
14                                                    NaN                       
...                                                   ...                       
278846                                                NaN                       
278849                                                NaN                       
278851                                                NaN                       
278852                                                NaN                       
278854                                                NaN                       

Title   ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
ID                                                                     
8                                                     NaN              
9                                                     NaN              
10                                                    NaN              
12                                                    NaN              
14                                                    NaN              
...                                                   ...              
278846                                                NaN              
278849                                                NaN              
278851                                                NaN              
278852                                                NaN              
278854                                                NaN              

Title   01-01-00: A Novel of the Millennium  \
ID                                            
8                                       NaN   
9                                       NaN   
10                                      NaN   
12                                      NaN   
14                                      NaN   
...                                     ...   
278846                                  NaN   
278849                                  NaN   
278

In [42]:
#Impute those NaNs with 0 values
user_books.fillna(0, inplace=True)    

In [43]:
user_books

Title    Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
ID                                                                         
8                        0.0                                         0.0   
9                        0.0                                         0.0   
10                       0.0                                         0.0   
12                       0.0                                         0.0   
14                       0.0                                         0.0   
...                      ...                                         ...   
278846                   0.0                                         0.0   
278849                   0.0                                         0.0   
278851                   0.0                                         0.0   
278852                   0.0                                         0.0   
278854                   0.0                                         0.0   

Title    Repairing PC Drives &amp  '48  \
ID                                       
8                             0.0  0.0   
9                             0.0  0.0   
10                            0.0  0.0   
12                            0.0  0.0   
14                            0.0  0.0   
...                           ...  ...   
278846                        0.0  0.0   
278849                        0.0  0.0   
278851                        0.0  0.0   
278852                        0.0  0.0   
278854                        0.0  0.0   

Title   'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
ID                                                                              
8                                                     0.0                       
9                                                     0.0                       
10                                                    0.0                       
12                                                    0.0                       
14                                                    0.0                       
...                                                   ...                       
278846                                                0.0                       
278849                                                0.0                       
278851                                                0.0                       
278852                                                0.0                       
278854                                                0.0                       

Title   ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
ID                                                                     
8                                                     0.0              
9                                                     0.0              
10                                                    0.0              
12                                                    0.0              
14                                                    0.0              
...                                                   ...              
278846                                                0.0              
278849                                                0.0              
278851                                                0.0              
278852                                                0.0              
278854                                                0.0              

Title   01-01-00: A Novel of the Millennium  \
ID                                            
8                                       0.0   
9                                       0.0   
10                                      0.0   
12                                      0.0   
14                                      0.0   
...                                     ...   
278846                                  0.0   
278849                                  0.0   
278

In [44]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances #for cosine similiarity
from scipy.spatial.distance import cosine, correlation   # for correlation similiarity

In [45]:
#to check similiarity
user_sim = 1 - pairwise_distances( user_books.values, metric='cosine')      

In [46]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)

In [48]:
user_sim_df 

0     1     2     3     4     5     6     7     8     9     ...  2172  \
0      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2177   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2178   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2179   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      2173  2174  2175  2176  2177  2178  2179  2180  2181  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2177   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0  
2178   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0  
2179   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  

[2182 rows x 2182 columns]

In [49]:
#Set the index and column names to user ids bcoz above it automattically assign index no. not a user id 
user_sim_df.index = books.ID.unique()
user_sim_df.columns = books.ID.unique()

In [50]:
user_sim_df.iloc[0:10, 0:10]   

276726  276729  276736  276737  276744  276745  276747  276748  \
276726     1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     1.0     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0   
276745     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0   
276747     0.0     0.0     0.0     0.0     0.0     0.0     1.0     0.0   
276748     0.0     0.0     0.0     0.0     0.0     0.0     0.0     1.0   
276751     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276754     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        276751  276754  
276726     0.0     0.0  
276729     0.0     0.0  
276736     0.0     0.0  
276737     0.0     0.0  
276744     0.0     0.0  
276745     0.0     0.0  
276747     0.0     0.0  
276748     0.0     0.0  
276751     1.0     0.0  
276754     0.0     1.0

In [51]:
 # Replace the 1 which is self make value replace by 0...not useful for further processs
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:10, 0:10]    

276726  276729  276736  276737  276744  276745  276747  276748  \
276726     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276745     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276747     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276748     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276751     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276754     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        276751  276754  
276726     0.0     0.0  
276729     0.0     0.0  
276736     0.0     0.0  
276737     0.0     0.0  
276744     0.0     0.0  
276745     0.0     0.0  
276747     0.0     0.0  
276748     0.0     0.0  
276751     0.0     0.0  
276754     0.0     0.0

In [52]:
#Most Similar Users
user_sim_df.idxmax(axis=1)[0:5] 

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
dtype: int64

In [53]:
bookclean[(bookclean['ID']==276729) |(bookclean['ID']==276726)]

ID                 Title  Rating
0  276726   Classical Mythology       5
1  276729          Clara Callan       3
2  276729  Decision in Normandy       6

- here 276729 and 276726 user have similiarties..so we can recommand 276729's watch movies to 276726 user.but highly recommmanded movie is 'Decision in Normandy' because it has high rating.